apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: dinesh-lab
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "145942781075"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: jxsetup
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: jenkinsxgitorg
    repository: jx3-gke-gsm
  - key: staging
  - key: production
  ingress:
    domain: 34.67.12.99.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: dineshgitbot
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-dinesh-lab-3ec8e0c1db40
  - name: reports
    url: gs://reports-dinesh-lab-3ec8e0c1db40
  - name: repository
    url: gs://repository-dinesh-lab-3ec8e0c1db40
  vault: {}
  webhook: lighthouse
